### ISSUE TITLE
DaemonSet Plugin Status not Aggregated

### ISSUE THREAD

**Issue by zs-ddl** [vmware-tanzu/sonobuoy#972]
**What steps did you take and what happened:**

Run a custom sonobuoy plugin Daemonset.

Sonobuoy status is split across multiple lines even when the status is the same for each Daemonset run. 
Even when successfully passed, the output contains multiple lines.

```
$ sonobuoy status
   PLUGIN     STATUS   RESULT   COUNT
   custom   complete   failed       1
   custom   complete                4

Sonobuoy has completed. Use `sonobuoy retrieve` to get results.
```

**What did you expect to happen:**

Status to output a single line:
```
$ sonobuoy status
   PLUGIN     STATUS   RESULT   COUNT
   custom   complete   failed       5

Sonobuoy has completed. Use `sonobuoy retrieve` to get results.
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: 
```$ sonobuoy version
Sonobuoy Version: v0.16.0
MinimumKubeVersion: 1.14.0
MaximumKubeVersion: 1.16.99
GitSHA: 6db0b0b7afeb904b2883bb8c3f379a47b5d01b44
```
- Kubernetes version: (use `kubectl version`):
```$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.13", GitCommit:"acdb9a03a6dc0f7f62d7acdda75c9a9faca50fee", GitTreeState:"clean", BuildDate:"2019-09-20T23:13:58Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: `1.14.6-gke.13`
- Cloud provider or hardware configuration: `1.14.6-gke.13`
- OS (e.g. from `/etc/os-release`): `Container-Optimized OS (cos)`
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
Thanks for the bug report; it was the same symptom I saw when creating #900  .
It has been resolved by https://github.com/vmware-tanzu/sonobuoy/pull/937 and went into the Sonobuoy 0.16.2 release.

**Comment by zs-ddl** [comment]
Unfortunately I still experience this issue even with 0.16.2 release

```
$ sonobuoy status 
   PLUGIN     STATUS   RESULT   COUNT
   custom   complete                1
   custom   complete   failed       1

Sonobuoy has completed. Use `sonobuoy retrieve` to get results.
```

```
$ sonobuoy version --kubeconfig ~/.kube/config
Sonobuoy Version: v0.16.2
MinimumKubeVersion: 1.14.0
MaximumKubeVersion: 1.16.99
GitSHA: 
API Version:  v1.14.6-gke.13
```

**Comment by zs-ddl** [comment]
@johnSchnake can we reopen this issue?

**Comment by johnSchnake** [comment]
@zs-ddl this information comes from processing done on the server side at, not from the client after the fact.

I'm guessing that you updated your client to v0.16.2 and retried the command on the older sonobuoy run? In that case you would see the same problem.

Let me know if that isnt the case; and if so, provide me with the output from `kubectl get pod sonobuoy -n sonobuoy -o json`

**Comment by zs-ddl** [comment]
You're correct @johnSchnake , a destroy of the sonobuoy server and rerun fixed the issue. Thanks!
